### ISSUE TITLE
Walking into a "noclip area"

### ISSUE THREAD

**Issue by jazluvr449** [bfeber/HLA-NoVR#138]
I just killed the gunner at the start of arms race, and I get to where you open the door to see about 4 zombies, but it's a noclip scene. I've had it once before, another time it was gone, now it's back again with the latest update.

I don't know how to post a screenshot.

I'm sorry to post so many issues, but I can't make any progress. I'll try to restart the 'puter and see what happens. I tried to upload it, i saved 2 in my steam page, name is jazluvr

**Comment by jazluvr449** [comment]
is anybody reading the "issues page anymore? Or am I just seeming like a "complainer? I don't know how someone was able to play all the way through the game to the credits, and post a utube playthrough, "which was very good!" and I'm have all kinds of problems here...lol.

**Comment by bfeber** [comment]
We had someone else have a similar issue I think, but I still don't know how to reproduce this. Unless I encounter it myself or someone has a video of the chapter where this bug happens (most likely when you somehow skip an area, since someone had it happen in VR once on the Steam forums) then I would be able to prevent it.

**Comment by jazluvr449** [comment]
I found a work-around, or maybe this is just the way the game plays...I had to go out on the roof (arms race) and re-enter through the door that was locked from inside, and i was able to finish the chapter, see the double door, open it, and kill the 4 zombies and progress from there.

**Comment by bfeber** [comment]
Fixed
