### ISSUE TITLE
Missing weapon upgrades

### ISSUE THREAD

**Issue by salem83** [bfeber/HLA-NoVR#147]
I only can see 2 upgrades per weapon. I'm really far into the game (Chapter "Jeff")

![image](https://github.com/bfeber/HLA-NoVR/assets/453737/2b6847d3-5668-4991-b21f-7bd1faeeb3a9)

**Comment by SnuggleBucketsNathan** [comment]
I'm pretty sure the modders pretty much just disabled all other except 2 (zoom + burst for pistol, zoom + RoF for SMG, double shot + "grenade launcher" [in reality a quick grenade throw key] for shotty)

It's pretty clear they haven't figured out how to implement the others yet since visual upgrades are disabled from the weapon models, and of course a laser sight and the normal reflex sight are nullified by the current aiming implementation which is just arcade Half-Life.

I do appreciate the zoom, but hopefully the weapons will behave like they do in VR eventually with all upgrades available.
