### ISSUE TITLE
Suggestion: Add Controller Support

### ISSUE THREAD

**Issue by humanlyhuman** [bfeber/HLA-NoVR#52]
For a Xbox or a Dualschock controller

**Comment by mebalzer** [comment]
Use DS4Windows or DualSenseWindows and use the settings for WASD emulation and modify to your liking.  I am currently trying to map Steam Remote for the same capability with my prototype "Gaming Lens" product that will allow LCD screens or tablets to be used with either a Dual Sense, DualShock 4 or a newer XBOX controller by floating the screen above the controller magnetically.  This allows for CoG balanced controller that is still lighter than a SteamDeck or many of the SmartPhone to Gamepad brackets.  Also by using one of the above apps, you can also program the Gyro to allow moving just like if you had a VR HMD on.  Kind of the best of both worlds.  Dead Space Remake is SO much more immersive this way (just remember to turn off 'Auto Aim' otherwise it disables Gyro when you need it the most -- while aiming).

**Comment by humanlyhuman** [comment]
There's glosl too but it doesn't seem to work with hlalyx

**Comment by Spider-Man1212** [comment]
There is controller support. 

https://youtu.be/n_1z9OG_6mw

**Comment by bfeber** [comment]
Not planned for now, use this method:

> There is controller support.
> 
> https://youtu.be/n_1z9OG_6mw
